# Generated by Django 4.2 on 2024-08-01 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
